spring:
  main:
    banner-mode: off
  application:
    name: routin-test
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: routin-user
    password: routin-password
    url: jdbc:postgresql://localhost:5433/routindb
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-root.xml
    contexts: null
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
